pipeline {
     agent any
     triggers {
          pollSCM('* * * * *')
     }
     stages {
          stage("Compile") {
               steps {
                    sh "cd Chapter08/sample1 && ./gradlew compileJava"
               }
          }
          stage("Unit test") {
               steps {
                    sh "cd Chapter08/sample1 && ./gradlew test"
               }
          }
          stage("Code coverage") {
               steps {
                    sh "cd Chapter08/sample1 && ./gradlew jacocoTestReport"
                    sh "cd Chapter08/sample1 && ./gradlew jacocoTestCoverageVerification"
               }
          }
          stage("Static code analysis") {
               steps {
                    sh "cd Chapter08/sample1 && ./gradlew checkstyleMain"
               }
          }

	  stage('Run Checkstyle') {
               steps {
                    // This command tells Jenkins to execute the Gradle checkstyle task
                    sh 'cd Chapter08/sample1 && ./gradlew checkstyleTest' 
               }
          }


	  stage('Publish Report') {
               steps {
                    // This uses the HTML Publisher plugin to make the report visible in Jenkins
                    publishHTML(target: [
                         allowMissing: false,
                         alwaysLinkToLastBuild: true,
                         keepAll: true,
                         reportDir: 'build/reports/checkstyle', // Standard output folder for Gradle checkstyle
                         reportFiles: 'test.html', 
                         reportName: 'jacoco checkstyle' // Name required by your instructions
                    ])
               }
          }


          stage("Package") {
               steps {
                    sh "cd Chapter08/sample1 && ./gradlew build"
               }
          }

          stage("Docker build") {
               steps {
                    sh "docker build -t leszko/calculator:${BUILD_TIMESTAMP} ."
               }
          }

          stage("Docker login") {
               steps {
                    withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'docker-hub-credentials',
                               usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
                         sh "docker login --username $USERNAME --password $PASSWORD"
                    }
               }
          }

          stage("Docker push") {
               steps {
                    sh "docker push leszko/calculator:${BUILD_TIMESTAMP}"
               }
          }

          stage("Update version") {
               steps {
                    sh "sed  -i 's/{{VERSION}}/${BUILD_TIMESTAMP}/g' calculator.yaml"
               }
          }
          
          stage("Deploy to staging") {
               steps {
                    sh "kubectl config use-context staging"
                    sh "kubectl apply -f hazelcast.yaml"
                    sh "kubectl apply -f calculator.yaml"
               }
          }

          stage("Acceptance test") {
               steps {
                    sleep 60
                    sh "chmod +x acceptance-test.sh && ./acceptance-test.sh"
               }
          }

          stage("Release") {
               steps {
                    sh "kubectl config use-context production"
                    sh "kubectl apply -f hazelcast.yaml"
                    sh "kubectl apply -f calculator.yaml"
               }
          }
          stage("Smoke test") {
              steps {
                  sleep 60
                  sh "chmod +x smoke-test.sh && ./smoke-test.sh"
              }
          }
     }
}
